name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs: 
  deployment-pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: npm install
        run: npm install
      - name: npm install
        working-directory: ./bloglist-frontend
        run: npm install
      - name: build
        run: npm run build:front  
      - name: eslint
        working-directory: ./bloglist-frontend
        run: npm run lint
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3001
      - name: heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cryptic-dawn-47996"
          heroku_email: "elsi.silvennoinen@gmail.com"
          healthcheck: "https://cryptic-dawn-47996.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      